import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/header";
import Footer from "./components/footer";
import localFont from "next/font/local";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const oceanic = localFont({
  src: "../public/fonts/TRIAL_Oceanic-Regular.otf",
});

const oceanic_m = localFont({
  src: "../public/fonts/TRIAL_Oceanic-Medium.otf",
});

const gilroy_r = localFont({
  src: "../public/fonts/Gilroy-Light.otf",
});

const gilroy_b = localFont({
  src: "../public/fonts/Gilroy-ExtraBold.otf",
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${oceanic.className} ${oceanic_m.className} ${gilroy_r.className}  antialiased`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
